[notice]
title = "티켓링크"
url = "http://www.ticketlink.co.kr/help/notice"
entrySelector = "tbody[id='nTableBody'] tr"
titleSelector = "td.tl.p_reative > a"
linkSelector = "td a"
contentSelector = "td:nth-child(3)"
waitForSelector = ".basic_tbl"
onFail = "stale"

[notice_m]
title = "티켓링크 모바일"
url = "http://m.ticketlink.co.kr/help/notice"
entrySelector = "ul.detail_content li"
titleSelector = "h3"
linkSelector = "a"
contentSelector = "a > dl > dd:nth-child(2)"
onFail = "stale"
